version: '3'
services:
  mongodb:
    image: mongo:4
    container_name: mongo-pwndoc-ng
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB=pwndoc
    networks:
      - backend

  backend:
    build: ./backend
    image: pwndoc-ng/pwndoc-ng:backend
    container_name: pwndoc-ng-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    environment:
      - COLLAB_WEBSOCKET_PORT=8440
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks:
      - backend

  frontend:
    build: ./frontend
    image: pwndoc-ng/pwndoc-ng:frontend
    container_name: pwndoc-ng-frontend
    restart: always
    environment:
      - Java_Xms=512m
      - Java_Xmx=2g
    ports:
      - 8443:8443
    networks:
      - backend
  languagetool:
    image: erikvl87/languagetool
    container_name: pwndoc-ng-languagetool
    restart: always
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: pwndoc-ollama
    volumes:
      - ollama-models:/root/.ollama
      - ./backend/scripts:/app/scripts
    ports:
      - "127.0.0.1:11434:11434"
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '4'
        reservations:
          memory: 8G
          cpus: '2'
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_MODEL=mistral
      - "OLLAMA_MODEL_PARAMS={\"temperature\": 0.3, \"top_p\": 0.8}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: ["/app/scripts/init-ollama.sh"]
    command: ["serve"]
    restart: always
    networks:
      - backend

volumes:
  mongo-data:
  ollama-models:

networks:
  backend:
      driver: bridge
