version: '3'
services:

  mongodb-test:
    image: mongo:4.2.15
    container_name: mongo-pwndoc-ng-test
    volumes:
      - ./mongo-data-test:/data/db
    restart: always
    environment:
      - MONGO_DB:pwndoc-ng
    network_mode: host

  backend-test:
    image: yeln4ts/pwndoc-ng:backend-test
    build: 
      context: .
      dockerfile:  Dockerfile.test
    container_name: pwndoc-ng-backend-test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./jest.config.js:/app/jest.config.js
    environment:
      API_URL: https://localhost:4242
    depends_on:
      - mongodb-test
    network_mode: host

  ollama-test:
    image: ollama/ollama:latest
    container_name: pwndoc-ollama-test
    volumes:
      - ollama-models-test:/root/.ollama
      - ./scripts:/app/scripts
    ports:
      - "127.0.0.1:11434:11434"
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '4'
        reservations:
          memory: 8G
          cpus: '2'
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_MODEL=mistral
      - "OLLAMA_MODEL_PARAMS={\"temperature\": 0.3, \"top_p\": 0.8}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: ["/app/scripts/init-ollama.sh"]
    command: ["serve"]
    restart: always
    network_mode: host

volumes:
  mongo-data-test:
  ollama-models-test:
